name: Python Flask CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: sudo apt-get install -y jq
  
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: docker build -t my-flask-app:${{ github.sha }} .

      - name: Run Docker container for unit tests
        run: docker run --name flask-unit-tests my-flask-app:${{ github.sha }} python -m unittest test-app.py

      - name: Start Selenium Service
        run: docker run -d --name selenium-standalone -p 4444:4444 selenium/standalone-chrome:latest

      - name: Wait for Selenium service to be ready
        run: |
          until curl -sSL "http://localhost:4444/wd/hub/status" | jq -r '.value.ready' | grep 'true' > /dev/null; do
            echo 'Waiting for the Selenium service...'
            sleep 5
          done

      - name: Run integration tests with Selenium
        run: timeout 5m python test-endtoend-app.py
        env:
          SELENIUM_DRIVER_URL: http://localhost:4444/wd/hub
          APP_URL: http://localhost:5000

      - name: Log in to DockerHub
        if: success()
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image to DockerHub
        if: success()
        run: docker push my-flask-app:${{ github.sha }}

      - name: Cleanup
        run: |
          docker rm -f flask-unit-tests
          docker rm -f selenium-standalone
      
      - name: Remove Docker image
        run: docker rmi my-flask-app:${{ github.sha }}
    