name: Python Flask CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: python -m unittest test_app.py

      - name: Build Docker image for Flask application
        run: docker build -t my-flask-app .

      - name: Wait for Selenium service to be ready
        run: |
          until curl -sSL "http://localhost:4444/wd/hub/status" | jq -r '.value.ready' | grep 'true' > /dev/null; do echo 'Waiting for the Selenium service...'
          sleep 5
          done

      - name: Start Flask application
        run: docker run -d --network host my-flask-app

      - name: Run integration tests
        run: docker run --network host -v ${GITHUB_WORKSPACE}:/app my-flask-app python /app/test_integration.py

      - name: Cleanup
        run: |


      - name: Cleanup
        run: |
          docker stop $(docker ps -aq)
          docker rm $(docker ps -aq)
          docker rmi my-flask-app
    
