name: Python Flask CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: python -m unittest test-app.py

      - name: Build Docker image for Flask application
        run: docker build -t my-flask-app .

      - name: Wait for Selenium service to be ready
        run: |
          until curl -sSL "http://localhost:4444/wd/hub/status" | jq -r '.value.ready' | grep 'true' > /dev/null; do echo 'Waiting for the Selenium service...'
          sleep 5
          done

      - name: Run integration tests
        run: docker run --network host my-flask-app