name: Python Flask CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start Flask app in the background
      run: |
        export FLASK_APP=app.py
        flask run &
      working-directory: ./

    - name: Install Selenium and WebDriver
      run: |
        pip install selenium
        sudo apt-get update
        sudo apt-get install -y chromium-chromedriver

    - name: Run integration tests with Selenium
      run: python test-endtoend-app.py
      env:
        SELENIUM_DRIVER_URL: http://localhost:4444/wd/hub
        APP_URL: http://localhost:5000

    - name: Build Docker image
      run: docker build -t my-flask-app .

    - name: Log in to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push Docker image to DockerHub
      run: docker push my-flask-app

    - name: Kill Flask app
      run: kill %1
